apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "makerkit-redis.fullname" . }}
  labels:
    app: {{ include "makerkit-redis.name" . }}
    chart: {{ include "makerkit-redis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "makerkit-redis.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "makerkit-redis.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6379
          resources:
{{ toYaml .Values.resources | indent 12 }}
          args: ["--save","","--appendonly","no"]
