image:
  repository: makerkit/worker
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  LOG_LEVEL: info
  CELERY_ENABLED: "1"

redis:
  url: redis://redis:6379/0
