apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "makerkit-worker.fullname" . }}
  labels:
    app: {{ include "makerkit-worker.name" . }}
    chart: {{ include "makerkit-worker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "makerkit-worker.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "makerkit-worker.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python","-m","celery","-A","apps.api.tasks","worker","--loglevel=INFO"]
          env:
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            - name: CELERY_ENABLED
              value: {{ .Values.env.CELERY_ENABLED | quote }}
            - name: REDIS_URL
              value: {{ .Values.redis.url | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
