apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: makerkit-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: makerkit-api
                port:
                  number: 80
    - host: diffusion.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: makerkit-diffusion
                port:
                  number: 80
