apiVersion: v1
kind: Service
metadata:
  name: {{ include "makerkit-diffusion.fullname" . }}
  labels:
    app: {{ include "makerkit-diffusion.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "makerkit-diffusion.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
